volumes:
  pg_data:

services:
  postgres:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - $DATABASE_PORT:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DATABASE_USER"]
      interval: 10s
      timeout: 5s
      retries: 5